baseline: Things from beccas mind
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
description: Whats on your mind today?
baseurl: /
date:
  format: j F Y
  timezone: Europe/Paris
postprocess:
  enabled: true
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Beccas site
canonicalurl: true
